### ISSUE TITLE
Cannot attach VHD on a net share

### ISSUE THREAD

**Issue by gadget1999** [medo64/VhdAttach#9]
The application can load information about VHD on a net share, but it fails with Attach action, saying file not found. Diskpart can mount the VHD on net share, is this a bug? Thanks

**Comment by medo64** [comment]
Yes and no. :)

It's not a bug as such but consequence of VHD Service being installed as a local system service. However, you can [adjust this](https://www.medo64.com/vhdattach/faq/) by changing the rights of VHD Attach service to match your user.

Go to the `Computer Management` -> `Services and Applications` -> `Services` and there find “VHD Attach” service. Right-click properties and then go to `Log On` tab. Instead of `Local System` account select `This account` and fill your user data.

After service restart you should be able to attach from network location also.
